const arrRepoLocations = [
  'netlify',
  'Jamstack',
  'Lorem-ipsum-generator',
  'medical',
  'serverless',
  'react',
  'countdown',
  'hacktoberfest',
  'http',
  'status-codes',
  'gifts',
  'rihanna',
  'donation',
  'landing-page'
];

const repositoryID = 10;
const arrRepositories = [{
  repoID: 0,
  repoTitle: 'greys-anatomy-lorem-ipsum-generator',
  repoLink: 'https://github.com/thedigitalmenagerie/sorting-hat',
  repoDescription: "A lorem generator with medical terms and words from the show Grey's Anatomy.",
  repoPinnedIcon: './images/tack-1.png',
  repoLanguageIcon: '../images/yellow-square.png',
  repoStarIcon: './images/star-2.png',
  repoForkedIcon: './images/fork-2.png',
  repo3DotIcon: './images/3-dot-icon.webp ',
  repoLanguage: 'javascript',
  starsCount: 168,
  pinned: false,
  repoMITLicense: false,
  issuesNeedHelp: 1,
  repoLastUpdate: 7,
  reposForked: 10,
  arrListOfButtons: [
    'netlify',
    'Jamstack',
    'Lorem-ipsum-generator',
    'medical',
    'serverless',
    'react'
  ]
},
{
  repoID: 1,
  repoTitle: 'how-many-days-until',
  repoLink: 'https://github.com/thedigitalmenagerie/pet-adoption',
  repoDescription: 'A React countdown app of days between today and next year.',
  repoPinnedIcon: './images/tack-1.png',
  repoLanguageIcon: '../images/yellow-square.png',
  repoStarIcon: './images/star-2.png',
  repoForkedIcon: './images/fork-2.png',
  repo3DotIcon: './images/3-dot-icon.webp ',
  repoLanguage: 'javascript',
  starsCount: 491,
  pinned: false,
  repoMITLicense: true,
  issuesNeedHelp: 0,
  repoLastUpdate: 1,
  reposForked: 21,
  arrListOfButtons: [
    'react',
    'countdown',
    'hacktoberfest'
  ]
},
{
  repoID: 2,
  repoTitle: 'httriri',
  repoLink: 'https://github.com/lindseysatterfield/sorting-hat ',
  repoDescription: 'HTTRiRi - HTTP Status Codes as Portrayed by Rihanna Gifs',
  repoPinnedIcon: './images/tack-1.png',
  repoLanguageIcon: './images/blue-square-2.jpg',
  repoStarIcon: './images/star-2.png',
  repoForkedIcon: './images/fork-2.png',
  repo3DotIcon: './images/3-dot-icon.webp ',
  repoLanguage: 'TypeScript',
  starsCount: 37,
  pinned: false,
  repoMITLicense: true,
  issuesNeedHelp: 4,
  repoLastUpdate: 6,
  reposForked: 12,
  arrListOfButtons: [
    'http',
    'status-codes',
    'gifts',
    'rihanna',
    'hacktoberfest'
  ]
},
{
  repoID: 3,
  repoTitle: 'ambition-found-website',
  repoLink: 'https://github.com/lindseysatterfield/pet-adoption',
  repoDescription: 'Website for www.ambition.cor, micro-grant program to provide support for underrepresented people who need financial assistance purging professional development opportunities in the technology...',
  repoPinnedIcon: './images/tack-1.png',
  repoLanguageIcon: '../images/yellow-square.png',
  repoStarIcon: './images/star-2.png',
  repoForkedIcon: './images/fork-2.png',
  repo3DotIcon: './images/3-dot-icon.webp',
  repoLanguage: 'javascript',
  starsCount: 32,
  pinned: false,
  repoMITLicense: true,
  issuesNeedHelp: 3,
  repoLastUpdate: 2,
  reposForked: 45,
  arrListOfButtons: [
    'donation',
    'landing-page'
  ]
},
{
  repoID: 4,
  repoTitle: 'honey-rae-sorting-hat',
  repoLink: 'https://github.com/thedigitalmenagerie/sorting-hat',
  repoDescription: "A lorem generator with medical terms and words from the show Grey's Anatomy.",
  repoPinnedIcon: './images/tack-1.png',
  repoLanguageIcon: './images/red-square.png',
  repoStarIcon: './images/star-2.png',
  repoForkedIcon: './images/fork-2.png',
  repo3DotIcon: './images/3-dot-icon.webp',
  repoLanguage: 'HTML',
  starsCount: 76,
  pinned: true,
  repoMITLicense: false,
  issuesNeedHelp: 1,
  repoLastUpdate: 5,
  reposForked: 11,
  arrListOfButtons: [
    'netlify',
    'Jamstack',
    'Lorem-ipsum-generator',
    'medical',
    'serverless',
    'react'
  ]
},
{
  repoID: 5,
  repoTitle: 'ls-sorting-hat',
  repoLink: 'https://github.com/lindseysatterfield/sorting-hat',
  repoDescription: "A lorem generator with medical terms and words from the show Grey's Anatomy.",
  repoPinnedIcon: './images/tack-1.png',
  repoLanguageIcon: './images/blue-square-2.jpg',
  repoStarIcon: './images/star-2.png',
  repoForkedIcon: './images/fork-2.png',
  repo3DotIcon: './images/3-dot-icon.webp',
  repoLanguage: 'Typescript',
  starsCount: 21,
  pinned: false,
  repoMITLicense: false,
  issuesNeedHelp: 1,
  repoLastUpdate: 7,
  reposForked: 51,
  arrListOfButtons: [
    'netlify',
    'Jamstack',
    'Lorem-ipsum-generator',
    'medical',
    'serverless',
    'react'
  ]
},
{
  repoID: 6,
  repoTitle: 'lindsey-pet-adoption',
  repoLink: 'https://github.com/lindseysatterfield/pet-adoption',
  repoDescription: "A lorem generator with medical terms and words from the show Grey's Anatomy.",
  repoPinnedIcon: './images/tack-1.png',
  repoLanguageIcon: './images/red-square.png',
  repoStarIcon: './images/star-2.png',
  repoForkedIcon: './images/fork-2.png',
  repo3DotIcon: './images/3-dot-icon.webp',
  repoLanguage: 'HTML',
  starsCount: 103,
  pinned: true,
  repoMITLicense: false,
  issuesNeedHelp: 1,
  repoLastUpdate: 10,
  reposForked: 7,
  arrListOfButtons: [
    'netlify',
    'Jamstack',
    'Lorem-ipsum-generator',
    'medical',
    'serverless',
    'react'
  ]
},
{
  repoID: 7,
  repoTitle: 'dc-personal-bio-site',
  repoLink: 'https://github.com/danicrosby/personal-bio-site',
  repoDescription: "A lorem generator with medical terms and words from the show Grey's Anatomy.",
  repoPinnedIcon: './images/tack-1.png',
  repoLanguageIcon: '../images/yellow-square.png',
  repoStarIcon: './images/star-2.png',
  repoForkedIcon: './images/fork-2.png',
  repo3DotIcon: './images/3-dot-icon.webp',
  repoLanguage: 'javascript',
  starsCount: 42,
  pinned: true,
  repoMITLicense: false,
  issuesNeedHelp: 1,
  repoLastUpdate: 5,
  reposForked: 11,
  arrListOfButtons: [
    'netlify',
    'Jamstack',
    'Lorem-ipsum-generator',
    'medical',
    'serverless',
    'react'
  ]
},
{
  repoID: 8,
  repoTitle: 'dani-sorting-hat',
  repoLink: 'https://github.com/danicrosby/sorting-hat',
  repoDescription: "A lorem generator with medical terms and words from the show Grey's Anatomy.",
  repoPinnedIcon: './images/tack-1.png',
  repoLanguageIcon: './images/red-square.png',
  repoStarIcon: './images/star-2.png',
  repoForkedIcon: './images/fork-2.png',
  repo3DotIcon: './images/3-dot-icon.webp',
  repoLanguage: 'HTML',
  starsCount: 16,
  pinned: false,
  repoMITLicense: false,
  issuesNeedHelp: 1,
  repoLastUpdate: 2,
  reposForked: 16,
  arrListOfButtons: [
    'netlify',
    'Jamstack',
    'Lorem-ipsum-generator',
    'medical',
    'serverless',
    'react'
  ]
},
{
  repoID: 9,
  repoTitle: 'juan-sorting-hat',
  repoLink: 'https://github.com/JuanDavila1101/sorting-hat',
  repoDescription: "A lorem generator with medical terms and words from the show Grey's Anatomy.",
  repoPinnedIcon: './images/tack-1.png',
  repoLanguageIcon: './images/blue-square-2.jpg',
  repoStarIcon: './images/star-2.png',
  repoForkedIcon: './images/fork-2.png',
  repo3DotIcon: './images/3-dot-icon.webp',
  repoLanguage: 'Typescript',
  starsCount: 12,
  pinned: true,
  repoMITLicense: false,
  issuesNeedHelp: 1,
  repoLastUpdate: 7,
  reposForked: 60,
  arrListOfButtons: [
    'netlify',
    'Jamstack',
    'Lorem-ipsum-generator',
    'medical',
    'serverless',
    'react'
  ]
}
];

export { arrRepoLocations, repositoryID, arrRepositories };
